# Generated by Django 2.1 on 2018-08-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180823_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=15)),
                ('size', models.CharField(max_length=10)),
                ('needs', models.BooleanField(default=False)),
                ('bonded', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
