# Generated by Django 2.1 on 2018-08-23 14:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
