# Generated by Django 2.1 on 2018-08-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180824_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
    ]
