# Generated by Django 2.1 on 2018-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180826_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('American Bulldog', 'American Bulldog'), ('Australian Shepherd', 'Australian Shepherd'), ('Basset Hound', 'Basset Hound'), ('Beagle', 'Beagle'), ('Border  Collie', 'Border  Collie'), ('Boston  Terrier', 'Boston  Terrier'), ('Boxer', 'Boxer'), ('Chihuahua', 'Chihuahua'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Collie', 'Collie'), ('Corgi', 'Corgi'), ('Dachshund', 'Dachshund'), ('Dalmatian', 'Dalmatian'), ('Doberman Pinscher', 'Doberman Pinscher'), ('French Bulldog', 'French Bulldog'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Great Dane', 'Great Dane'), ('Greyhound', 'Greyhound'), ('Husky', 'Husky'), ('Italian Greyhound', 'Italian Greyhound'), ('Jack Russell Terrier', 'Jack Russell Terrier'), ('Labrador Retriever', 'Labrador Retriever'), ('Maltese', 'Maltese'), ('Mastiff', 'Mastiff'), ('Papillon', 'Papillon'), ('Pit Bull Terrier', 'Pit Bull Terrier'), ('Pomeranian', 'Pomeranian'), ('Poodle', 'Poodle'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Schnauzer ', 'Schnauzer '), ('Sheltie', 'Sheltie'), ('Shih Tzu', 'Shih Tzu'), ('Weimaraner', 'Weimaraner'), ('Yorkie', 'Yorkie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
