# Generated by Django 2.1 on 2018-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180826_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
